FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o worker .

FROM alpine:latest
# RUN apk --no-cache add ca-certificates   # закомментировать или удалить
WORKDIR /root/
COPY --from=builder /app/worker .
CMD ["./worker"]